spring.application.name=orderflow

# H2 in-memory database
#spring.datasource.url=jdbc:h2:mem:orderflowdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.url=jdbc:h2:mem:orderflowdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server
server.address=0.0.0.0
server.port=8080
#server.port=${PORT:5000}

# CORS
#cors.allowed-origins=http://localhost:3000,http://localhost:5173
cors.allowed-origins=*
# Anthropic AI
anthropic.api.key=shusdhfhsdfjsdfhjksdhf
#anthropic.api.key=${ANTHROPIC_API_KEY}
anthropic.model=claude-sonnet-4-20250514
anthropic.api.max-tokens=1024
